### ISSUE TITLE
Implement and publish PokeData JS API

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/PokeData#107]
The discussion about the API happens at https://github.com/PokemonGoers/Catch-em-all/issues/23 and I hope you all join us!

After the API spec has settled you're going to have to implement and ship it as an npm package, so that the map teams and us, the UI team, can use it. This of course is a lot of work, however, we, the UI team, will just use a stub implementation until you provide us with your implementation.

MajorBreakfast (Project E)

**Comment by jonas-he** [comment]
@MajorBreakfast I think youve already seen our first version of the API as you already mentioned it in your other post. You don't have to use a stub implementation, you simply have to call these URLs like http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/sighting/source/POKESNIPER. Why would you want to blow that up into a whole package?
Also in your architecture you got something slightly wrong: not only twitter but also the other data sources do contribute to the prediction.

**Comment by sacdallago** [comment]
Yup @MajorBreakfast you are mixing up things a bit.
PokeData IS the API, this is where you or any other team (map, predictions,...) Get their data :)
It doesn't make sense that the map people use this as an npm package, they should just use the API calls to get the data, should some calls be missing they can coordinate with this project to implement the new routes and where to get the data from.
The map trams will then package their product into npm packages which you will use. These packages will have the possibility to define where the endpoint for the API calls is, so that everything will work correctly.

**Comment by MajorBreakfast** [comment]
@jonas-he 
@sacdallago 
Let's keep the discussion in PokemonGoers/Catch-em-all#23

**Comment by MajorBreakfast** [comment]
The app team will develop the PokeData JS API
