### ISSUE TITLE
Twitter Listener for hashtag and event trigger

### ISSUE THREAD

**Issue by swathi-ssunder** [PokemonGoers/PokeData#13]

**Comment by samitsv** [comment]
- created a basic listener for #pokemongo: PR #18

**Comment by sacdallago** [comment]
@samitsv in your previous point, you mention you created a listener. I wonder where :)
To highlight where you have three options:
1. If you opened a pull request regarding this issue, you can reference this issue by inserting in the pull request description a #ISSUENUMBER ( #13 in this case)
2. If you solved the issue in one commit, you can close the issue by terminating your commit with "closes #ISSUENUMBER". The issue will be closed ONLY once the PR is approved. More: https://help.github.com/articles/closing-issues-via-commit-messages/
3. If you want to mention here the PR or the commit where you worked on the issue, you can do so by using #PRNUMBER or by copying the hash of the commit (go on commits, "copy full SHA of commit", paste here).

It is extremely important to start referencing issues, PRs, commits and LOCs the correct way, because soon I will have to read about 20 issues/discussions per hour and if you are not very precise, I get lost :)

**Comment by samitsv** [comment]
closed by #18 and #41
