### ISSUE TITLE
How the additional features should be stored

### ISSUE THREAD

**Issue by jonas-he** [PokemonGoers/PokeData#130]
I have implemented two additional features: `relativeTime` (which gives time of day at a given location and UTC time) and `environment` (which gives a classification of the environment at a given location according to this scheme http://glcf.umd.edu/data/lc/).
For that i have written two functions in `/app/services/common.js`. Now the question is if we want to expand our schema for the database and for every sighting compute this additional information upon insertion into the database OR we compute it upon calling our API if needed.
My opinion would be to take the second approach, because the other approach would add redundancy to the DB. However i heard that the machine learners would probably get a DB dump and dont  "squeeze out" our API so maybe the first approach is better ?

**Comment by bensLine** [comment]
@jonas-he nice job, thanks! :) looking forward to use the new features for our data!

**Comment by semioniy** [comment]
@jonas-he the environment feature is really cool. Thanx!

**Comment by jonas-he** [comment]
@sacdallago any thoughts on this?

**Comment by sacdallago** [comment]
Sorry. I read through this the first time but somehow forgot to answer. I'm getting old.

The idea is great, but I worry that this is out of scope.

If you want to imement it, definetly go with option two, but since this data is necessary only for the predictions, it should be encapsulated in their projects (as in: they associate a lat/long with terrain features internally, maybe by having a look up table / file based db, without performing further API calls).

By implementing this, potentially your API may be used for a completely different purpose, which is not nice :)

**Comment by sacdallago** [comment]
Oh. The above applies to the environment data, but for the relative time, I believe you can nest it in the original objects when you return (so, option 1)

**Comment by jonas-he** [comment]
relative time is implemented (see #158 ), environment feature code is adapted by the prediction group.
