### ISSUE TITLE
Data Extraction and Storage- Should it be a part of npm start ?

### ISSUE THREAD

**Issue by vivek-sethia** [PokemonGoers/PokeData#33]
Currently npm start does not perform data extraction and storing it into MongoDB. It is separately perfromed through npm run update --collection=<collection_name>.

**Comment by swathi-ssunder** [comment]
I also have a doubt regarding this.
In the Dockerfile, the last line is npm start. If the database storing is through the above npm update command, then will this command be executed manually? 
Or will it somehow be integrated into the Dockerfile?

**Comment by sacdallago** [comment]
Well it depends.
(Re)Building the database structure might be something you only wanna do at times, so by using `npm run build --collection...`.
On the other hand, feeding information to the database via listening on different services you should be doing constantly, so it should be part of your normal (start) execution.
You could however have some specialised behaviours, like `npm listen pokeradar` which would only listen to pokeradar and scrape the info from there... This is useful because if the service goes down you can simply stop using it or kill the process and respawn it later. Also you would have a model for other people to plug in new services in the future.
As for docker, you can tackle this behaviour using env variables or building different containers for each npm script (in the same dockerfile)

**Comment by vivek-sethia** [comment]
Thank you for the pointers.
1. Will the npm start also contains initial data collection ( previous data ) or will the npm build collection do that ?
2. How do we separate collections for the data storage based on data source( such as poke radar , pokeapi, twitter) or based on data attributes ? We feel that data collections should be based on source of the data rather data attributes  since it makes more sense as the data from a particular source will have the same set of value.
3. Could not find much on multiple containers in Dockerfile. Only leads which I found was docker compose. ( but not sure how to use ? ) . I followed the following [link](http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html)

It will be helpful to get some more inputs/suggestions.

**Comment by sacdallago** [comment]
1. I don't quote get the question. For what I understand/the way I would build it: the start should expose the API, the build should build the database/scrape the static data from wiki pages, there should be several scripts to listen to different services (Twitter, pokeradar, what not) which will be running indefinitely.
2. Again, how I would do it: many services will share one collection with a flag telling the data source (`seen`, pokeradar, Twitter,...). Some services (services that scrape data from wiki pages, details about Pokémon aso, WHICH will not be constantly running but only run when the user wants to re-scrape the data, maybe every 6months) may also use the same collection, like `pomemons`, and for every Pokémon create an object with all its attributes. I don't think (for now) that you would need more than two collections.
3. Mh. I think docker compose would be too much. What you could do instead is not define the entry script (`[npm, start]`), and define what should be executed when you `docker run` the machine. You can for instance do `docker run some/image /bin/bash` and that will start the container by executing bash (Meaning that when you stop and restart the instance, it will restart by respawning bash... Cool, right?!).
   Alternatively you can aso use `docker exec` ( https://docs.docker.com/engine/reference/commandline/exec/ ) to run a command in a running container, but this would be meh, given that you would break the concept of isolation that docker does so nicely. I invite you to explore the options.

**Comment by sacdallago** [comment]
P.s.: sorry for typos, am on phone

**Comment by vivek-sethia** [comment]
@sacdallago 

As of now the scripts are as follows:
1. `npm start` - used for api set up.
2. `npm build` - used for building pokemon master details, info such as name, id , attacks etc.
3. `npm listen` - for listening the external api( such as Pokeradar, Pokesniper) and creating temporary files with the data. ( listening continuously)
4. `npm update` - reading the temporary files and storing the data in the MongoDB and deleting the files. ( inserts the data and process exits. )
   For twitter, there is a direct insertion of data into the database.

Do we need to update the database continuously or we can have a job which calls the update script and inserts into the database at a certain point in time?

**Comment by sacdallago** [comment]
@vivek-sethia thanks for the info, nice to read.

I would suggest you merge the listen and update. From my standpoint (this might though have a reason to exist) It's not of much use to write temporary file and have two separate processes listen and update the data in the database.
So. Yes: go for the "update the database continuously".
It might be worth mentioning that when you spawn a write action in the database (insert/create), an async call is produced, so the execution of the main thread is not really stopped and the child_process takes care of handling the write procedure, which is anyway performed outside of JS/Node.
If you don't define a callback function on the write (which you don't need to define, in my opinion) then you also avoid setting up a function in the event queue and the execution of the entire thing should be smoother.

If, say, you initiate 1000 writes but end up losing 1-5, that's not such a big deal!

**Comment by vivek-sethia** [comment]
@sacdallago Thanks for the inputs. In such case, we will only write to the database if we only have specified number of records( for e.g 100 ). Otherwise, if we write to the database for every data record then there will be too many database operations. Hope this is fine.

**Comment by sacdallago** [comment]
@vivek-sethia sure, makes totally sense and I see why you would do that :) It's not an easy thing to take care of, but having temp files on the server is always scary (to me) :D

**Comment by vivek-sethia** [comment]
@sacdallago I am planning to move the extraction functionality to execute on npm start. I tried running these commands on start:  `NODE_ENV=production node app.js | npm run listen --collection=rarePokemon | npm run listen --collection=pokeRadar | npm run listen --collection=twitter`

Though it works, they will be listening to the external api of the data sources indefinitely.
I would like to know if this is the right approach.

**Comment by sacdallago** [comment]
@vivek-sethia I would separate API from listeners!
If one of the listener breaks (because the service is down, because some routes change, because whatever) the API will still be up if you don't mix them. Maybe you can mix them in a way that it would still work anyway, but it would still be mixing different concerns... And how would you restart the listening without tearing down the API?

With docker you can EASILY spawn different containers executing different npm or node directives, aka

```
npm run listen --collection=rarePokemon
```

becomes

```
docker run --env-file /home/cdallago/pokemon/env --name rarePokemon -d pokemongoers/pokedata:develop npm run listen --collection=rarePokemon
```

And also they would always rebuild and be redeployed on changes in either develop or master (I can set up docker to listen to changes either/or).

The only listener that could operate with the API is twitter, because for that we know twitter won't die out any time soon.. But also there: what happens if you want to change the features (words) twitter listens too? :)

**Comment by vivek-sethia** [comment]
@sacdallago - Sure, this is what we discussed. However, I raised this question as one of our team members came up with this suggestion and we wanted to confirm.
The API will be separate from the listeners!
