### ISSUE TITLE
Schema of all the sources of pokemon data

### ISSUE THREAD

**Issue by samitsv** [PokemonGoers/PokeData#50]
**Twitter Schema**

``` javascript
new mongoose.Schema({
    tweetId: {
        type: String,
        unique: true
    },
    pokemonName: {
        type: String
    },
    foundAt: {       <--- location
        latitude: Number,
        longitude: Number,
    },
    appearedOn: {type: String}  <-- Date String
});
```

**Comment by vivek-sethia** [comment]
**Pokesniper - Rare Pokemon Schema**

```
rarePokemonSchema = new Schema({
    id         : {type: Number},
    name       : {type: String},
    latitude   : {type: Number},
    longitude  : {type: Number},
    spawn_time : {type: Date},
    seen_until : {type: Date},
    icon_url   : {type: String}

});
```

**Comment by jonas-he** [comment]
PokeRadar Schema

``` javascript
var pokeRadarSchema = new Schema({
    id         : {type: String},
    created    : {type: Number},
    downvotes  : {type: Number},
    upvotes    : {type: Number},
    latitude   : {type: Number},
    longitude  : {type: Number},
    pokemonId  : {type: Number},
    trainerName: {type: String},
    userId     : {type: String},
    deviceId   : {type: String}

});
```

**Comment by sacdallago** [comment]
@samitsv took the liberty to edit your comment to prettify the code

@PokemonGoers/pokedata I like this discussion. In my opinion, at the ond of the day, you should have **one** schema for all sources. But I guess that's what you were also thinking about

**Comment by samitsv** [comment]
Common Schema decided:

``` javascript
var pokemonSightings = new Schema({
      source:{type: Number},
      location: {type: String, coordinates: [Number]},
      pokemonId: {type: Number},
      appearedDate:{type: Date}
)};
```

**Comment by sacdallago** [comment]
Why is `source` a `Number`? I suggest: keep it simple, make it `String` ;)

**Comment by sacdallago** [comment]
P.S.: otherwise you have to map services to numbers, and vice versa

**Comment by jonas-he** [comment]
The idea was to save disk space, as a Number is 8 bytes in size and e.g. "PokeRadar" encoded in UTF-8 is 9 bytes :smile:

**Comment by jonas-he** [comment]
defined sources as follows (in the config):

```
"pokemonDataSources": {
        "pokeSnipers": 1,
        "pokeRadar": 2,
        "twitter": 3
    }
```

**Comment by sacdallago** [comment]
@jonas-he I get it, this is a design decision rather than anything else... and it's a trade of: space over comprehensibility. But since we are in the era of [3TB for <100E in first-world countries](https://www.amazon.de/Blue-WD30EZRZ-Interne-Festplatte-Zoll/dp/B013HNYV42/ref=sr_1_2?ie=UTF8&qid=1472096370&sr=8-2&keywords=3tb) and LTE I don't think there's such a super huge need to sacrifice comprehensibility over space **for this specific case**. Sure: if you were to store the same image 200 times, then I would be more prone to implement a mapping :)
Also: the services may die out, change, etc. Most importantly: you can uncouple the config from the script that mines the sources!!! (meaning, if you add a service and add data from this service to the DB the running API will automatically know from which service it comes if the data stores the sources as a string. On the other hand: you would **not** know it if you had to rewrite aka repull, respawn the API and reload the config --> Basically we are talking: bringing down the API vs not bringing down the API).

**Comment by samitsv** [comment]
``` javascript
new Schema({
    source        : {type: String},
    location      : {type: {type: String, default: 'Point'}, coordinates: [Number]},
    pokemonId     : {type: Number},
    appearedOn    : {type: Date}
});
```
