### ISSUE TITLE
Some basic documentation

### ISSUE THREAD

**Issue by phdowling** [PokemonGoers/PokeData#60]
Hey guys, Project C here. We were told to collaborate with you on gathering data from the twitter streaming API and the regular twitter API, which we will apply sentiment analysis and some sort of anomaly detection to. 

Could you give a basic overview of the status of this project and how to use the code? Is there some sort of way to include your work as a library and have some methods to call to query for certain tweets?

Cheers,
Philipp

**Comment by phdowling** [comment]
More specifically: 
1. We need a way to query live tweets for all pokemon, and if they are location tagged, we also need the coordinates. Is this already implemented here, or do we need to do this?
2. We need to query the regular API for the same information to get historic tweets. Is this part of your project already?

**Comment by fabe85** [comment]
Hi Philipp,

up to this moment we plan to contribute an api which you can connect to. In addition, the twitter stream provides in fact live tweets filtered by some keywords like "pokemonfound". The coordinates are also provided by us in GeoJSON format, i.e. you get the longitude and the latitude. Right now if you want to trigger the database to collect tweets you can do that by typing "npm run listen --collection=twitter", but that might change in some days.
I hope I could help you a bit and give you a rough overview. But don't hesitate to ask.

**Comment by jonas-he** [comment]
1. Im not in charge of our twitter thing but as I understand it we use the twitter streaming API to find live tweets about pokemon sightings (by looking for certain hashtags and keywords). We then try to parse the tweet and find out which pokemon was seen, use the timestamp of the tweet and the geo location to write this to our database for pokemon sightings (for the db we also have other sources apart from twitter).
2. As of now we only listen on live tweets and not on past tweets.

We will also provide an api to query our database. The main purpose of this is to deliver the data to the machine learning group, but i think we could also implement a filter (e.g. give all the pokemon sightings which have the source 'twitter') if this is what youre looking for.

**Comment by samitsv** [comment]
@phdowling  hello there, i have implemented the tweeter streaming service. As of now, we store the historical tweets (starting from the day) and live tweets to the database using our schema which would include the source as a field so that you can differentiate which data is from twitter, the latitude and longitude of the tweet will be added if there exist in the tweet data, and the pokemon id. The data added is filtered such that the following keywords are in the tweet

``` javascript
"twitterKeyWords" : 'pokemon catch,pokemon saw,pokemon attack,pokemon find,pokemon caught,pokemon attacked,pokemon found,pokemon appeared,#foundPokemon,#caughtPokemon,#pokemongo,a wild appeared until #pokemongo',
```

, and also i do a check whether a pokemon name out of 151 is in the tweet or not and then it is added to the database. This can be accessed by our api.
To see the twitter data, right now you would need to run mongodb locally and then use **CONSUMER_KEY="value"CONSUMER_SECRET="value" ACCESS_TOKEN="value"ACCESS_TOKEN_SECRET="value" npm start**, and for the **values** in the command you will need to create credentials in https://apps.twitter.com/, but this way of accessing the twitter data will change soon

**Comment by swathi-ssunder** [comment]
@phdowling - You could refer to the API [here](http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/).
